version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      PGRST_DB_URI:
      POSTGRES_DB: fleure_du_noir
      POSTGRES_USER: master
      POSTGRES_PASSWORD: changeme
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://master:changeme@db:5432/fleure_du_noir"
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_JWT_SECRET: "that-is-no-so-secret-but-still-32+-characters-long"
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
